Ria 6424 appeal submission summary
hmcts/ia-case-documents-api pull request #527
Opened 2023-01-03 14:06 UTC by hussain-faruk

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-6424
### Change description ###
Added some defs to AsylumCaseDefinitions to extract asylum case data
Added some putters to place case data in field values which docmosis can use in order to generate the appeal submission summary

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-01-03 14:11 UTC, hussain-faruk commented
After discussing with Neha and Marcello, extracting noms number is proving quite difficult using AsylumCaseDefinition, as the field is coming through as some complect data type rather than a simple string. So I have manually extracted the data and used regex matching to get the data I want. This is not an optimal solution but I cannot see how else it can be done. Nowhere else in the entire codebase (using ctrl+n) is noms number being extracted from asylumcasedata, so I cannot go by others work.

Same applied to prisoner release date.

2023-01-03 18:40 UTC, hussain-faruk commented
In a couple of tests, when asserting if number of fields in case data == number of fields in the mapped templateFieldValues, the values have been hard coded. I have not corrected this however I believe this should be ,changed.

2023-01-04 09:59 UTC, neha-aggarw commented on src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplate.java
> +            switch (detentionFacility) {
Just a suggestion, can you take the block related to setting fields of detention facility and move to a private method?

2023-01-06 16:47 UTC, neha-aggarw requested changes

2023-01-08 20:45 UTC, hussain-faruk commented on src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplateTest.java
> +    private String otherName = "{otherName=Other MoJ Facility}";
No. These fields come through from the UI to case asylum in the same format, so in the tests I have to replicate the same format. This is why the formatComplexString() method exists in AppealSubmissionTemplate.

2023-01-09 15:45 UTC, neha-aggarw approved these changes

2023-01-09 16:00 UTC, colmlynch60 approved these changes
LGTM

2023-01-09 16:00 UTC, merged