Ria 6605 ada suitability document api
hmcts/ia-case-documents-api pull request #547
Opened 2023-01-26 14:40 UTC by hussain-faruk

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-6605

### Change description ###
Added new template and handler for ADA suitability document

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-01-26 16:02 UTC, hussain-faruk commented
[DE 50002 2023-Dld-ADA-suitability-decision.PDF](https://github.com/hmcts/ia-case-documents-api/files/10511046/DE.50002.2023-Dld-ADA-suitability-decision.PDF)

Example ADA Suitability document attached

2023-01-26 16:31 UTC, ThomasKKC commented on src/main/resources/application.yaml
> +AdaSuitabilityDocument.contentType: application/pdf
Can you make the first char lower case like the rest?

2023-01-26 16:31 UTC, ThomasKKC requested changes

2023-01-26 16:31 UTC, ThomasKKC commented on src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AdaSuitabilityTemplateTest.java
> +
Can you fix the formatting here?

2023-01-26 16:36 UTC, ThomasKKC requested changes
We need to add functional tests for new template/scenario

2023-01-27 15:34 UTC, ThomasKKC approved these changes

2023-01-27 15:54 UTC, colmlynch60 approved these changes
LGTM - Thomas and Hussain has brought me through the required changes here

2023-01-27 15:55 UTC, merged