RIA-7200 Internal ADA generate hearing bundle document generation
hmcts/ia-case-documents-api pull request #602
Opened 2023-07-11 09:13 UTC by hussain-faruk

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-7200

### Change description ###
* Added generate hearing bundle doc generation for internal ADA cases
* Added unit/functional tests

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-07-11 10:27 UTC, neha-aggarw requested changes

2023-07-11 10:27 UTC, neha-aggarw commented on src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaGenerateHearingBundleTemplateTest.java
> +package uk.gov.hmcts.reform.iacasedocumentsapi.domain.templates;
Can we please use the letter package for all the notification related letter generation?

2023-07-11 10:27 UTC, neha-aggarw commented on src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaGenerateHearingBundleTemplate.java
> +package uk.gov.hmcts.reform.iacasedocumentsapi.domain.templates;
Can we please use the letter package for all the notification related letter generation?

2023-07-11 10:27 UTC, neha-aggarw commented on src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/InternalAdaGenerateHearingBundleHandler.java
> +package uk.gov.hmcts.reform.iacasedocumentsapi.domain.handlers.presubmit;
Can we please use the letter package for all the notification related letter generation?

2023-07-11 10:27 UTC, neha-aggarw commented on src/main/resources/application.yaml
> +internalAdaHearingBundle.templateName: ${IA_END_APPEAL_AUTOMATICALLY_TEMPLATE:TB-IAC-DEC-ENG-00007.docx}
can you please change the system variable name on line 157.

2023-07-11 10:27 UTC, neha-aggarw commented on src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/InternalAdaGenerateHearingBundleHandlerTest.java
> +package uk.gov.hmcts.reform.iacasedocumentsapi.domain.handlers.presubmit;
Can we please use the letter package for all the notification related letter generation?

2023-07-11 13:26 UTC, colmlynch60 submitted a review, later dismissed
LGTM

2023-07-11 16:54 UTC, ikirsanov submitted a review, later dismissed

2023-07-12 07:39 UTC, neha-aggarw requested changes

2023-07-12 07:39 UTC, neha-aggarw commented on src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalAdaGenerateHearingBundleHandler.java
> +                && callback.getEvent() == Event.GENERATE_HEARING_BUNDLE
Same concept for this as well. We need to check the async stitching event.

2023-07-13 07:33 UTC, ikirsanov approved these changes

2023-07-13 09:17 UTC, ikirsanov approved these changes

2023-07-13 11:32 UTC, neha-aggarw submitted a review, later dismissed

2023-07-13 13:44 UTC, colmlynch60 approved these changes
LGTM

2023-07-13 13:44 UTC, ikirsanov approved these changes

2023-07-13 13:44 UTC, merged