RIA-7328 ho_ftpa_submitted
hmcts/ia-case-documents-api pull request #657
Opened 2023-08-24 15:31 UTC by ikirsanov

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-7328

### Change description ###
Added Letter generator, DocumentCreatorConfiguration, Template for internal, detained cases with APPLY_FOR_FTPA_RESPONDENT event(for ada and non-ada). As well added tests, functional tests and roles for tests too.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-08-25 12:02 UTC, neha-aggarw requested changes

2023-08-25 12:02 UTC, neha-aggarw commented on src/functionalTest/resources/scenarios/RIA-7328-internal-detained-case-apply-for-ftpa-respondent-ada-letter.json
> +    "credentials": "HomeOfficePou",
Can you try changing to HomeOfficePOU?

2023-08-25 12:02 UTC, neha-aggarw commented on src/functionalTest/resources/scenarios/RIA-7328-internal-detained-case-apply-for-ftpa-respondent-non-ada-letter.json
> +    "credentials": "HomeOfficePou",
Same here.

2023-08-29 08:50 UTC, colmlynch60 approved these changes
LGTM

2023-08-29 09:23 UTC, merged