RIA-7439
hmcts/ia-case-documents-api pull request #729
Opened 2023-10-02 09:31 UTC by ikirsanov

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-7439

### Change description ###
Document generation for Internal HO Direction due date changed: ADA and non-ADA scenarios
Unit and functional tests

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-10-02 10:06 UTC, hussain-faruk commented on src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/InternalHoChangeDirectionDueDateLetterGenerator.java
> +    private boolean isDirectionPartyRespondent(AsylumCase asylumCase) {
Maybe we can move this to asylumCaseUtils for future use and avoid code dupes

2023-10-02 10:07 UTC, hussain-faruk approved these changes

2023-10-02 10:37 UTC, hussain-faruk requested changes
tests needed for added method in aslym case utils

2023-10-02 11:01 UTC, hussain-faruk submitted a review, later dismissed

2023-10-02 11:31 UTC, hussain-faruk approved these changes

2023-10-02 13:49 UTC, colmlynch60 approved these changes
LGTM

2023-10-03 07:45 UTC, jamieclarkeHMCTS approved these changes

2023-10-03 08:00 UTC, colmlynch60 approved these changes
LGTM

2023-10-03 08:02 UTC, jamieclarkeHMCTS approved these changes

2023-10-03 08:12 UTC, merged